version: '2'
services:
    supergooalros-app:
        image: supergooalros
        external_links:
            - supergooalros-postgresql:postgresql
            - supergooalros-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/supergooalros
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    supergooalros-postgresql:
        extends:
            file: postgresql.yml
            service: supergooalros-postgresql
    supergooalros-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: supergooalros-elasticsearch
