version: '2'
services:
    supergooalros-postgresql:
        container_name: supergooalros-postgresql
        image: postgres:9.5.2
        # volumes:
        #     - ~/volumes/jhipster/supergooalros/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=supergooalros
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
